[package]
name = "tune"
version = "0.5.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"

rodio = "0.21"

dirs = "6.0"
walkdir = "2.5"
lofty = "0.21"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
